

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ServiceLayerNew
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ModelMyHealth : DbContext
{
    public ModelMyHealth()
        : base("name=ModelMyHealth")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<TipoAlerta> TipoAlertaSet { get; set; }

    public virtual DbSet<FrequenciaCardiacaValores> FrequenciaCardiacaValoresSet { get; set; }

    public virtual DbSet<PressaoSanguineaValores> PressaoSanguineaValoresSet { get; set; }

    public virtual DbSet<SaturacaoValores> SaturacaoValoresSet { get; set; }

    public virtual DbSet<Utente> UtenteSet { get; set; }

    public virtual DbSet<AvisoFrequenciaCardiaca> AvisoFrequenciaCardiacaSet { get; set; }

    public virtual DbSet<AvisoSaturacao> AvisoSaturacaoSet { get; set; }

    public virtual DbSet<AvisoPressaoSanguinea> AvisoPressaoSanguineaSet { get; set; }

    public virtual DbSet<TipoAviso> TipoAvisoSet { get; set; }

}

}

