//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alerta()
        {
            this.FrequenciaCardiacaValore = new HashSet<FrequenciaCardiacaValores>();
            this.SaturacaoValore = new HashSet<SaturacaoValores>();
            this.PressaoSanguineaValore = new HashSet<PressaoSanguineaValores>();
        }
    
        public int Id { get; set; }
        public string Tipo { get; set; }
        public int ValorMinimo { get; set; }
        public int ValorMaximo { get; set; }
        public int ValorCriticoMinimo { get; set; }
        public int ValorCriticoMaximo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrequenciaCardiacaValores> FrequenciaCardiacaValore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaturacaoValores> SaturacaoValore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PressaoSanguineaValores> PressaoSanguineaValore { get; set; }
    }
}
