//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaturacaoValores
    {
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int Saturacao { get; set; }
    
        public virtual Utente Utente { get; set; }
        public virtual Alerta Alertas { get; set; }
    }
}
