//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utente
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string PressaoSanguinea { get; set; }
        public string SaturacaoOxigenio { get; set; }
        public string FrequenciaCardiaca { get; set; }
        public long SNS { get; set; }
    }
}
